version: '3.8'

services:
  home-safety-game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: home-safety-game
